# Generated by Django 4.2.5 on 2024-01-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=50)),
                ('course_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('about', models.TextField()),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
            ],
        ),
    ]
